
spring:
  application:
    name: common-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: deesan501@gmail.com
    password: Deelip#03
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
