
server:
  port: 8081
  servlet:
    context-path: /user-svc

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: deesan501@gmail.com
    password: Deelip#03
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
